apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      containers:
      - name: ecommerce-app
        image: krishnadas7/ecommerce-app:alpine
          