apiVersion: v1
kind: Service
metadata:
  name: ecommerce-srv
spec:
  type: NodePort
  selector:
    app: ecommerce-app
  ports:
    - name: ecommerce-app
      protocol: TCP
      port: 3000
      targetPort: 3000
